name: flutter_web_online_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  get: ^4.3.8
  flutter_svg: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  easy_localization: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - lib/ui/resources/png/
    - lib/ui/resources/translations/

